<a href="https://colab.research.google.com/github/thutrang7122005-ai/AIDEOM-VN/blob/master/kinh_t%E1%BA%BF_l%C6%B0%E1%BB%A3ng_%E1%BB%A9ng_d%E1%BB%A5ng.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files

uploaded = files.upload()

In [ ]:
import pandas as pd

df2011 = pd.read_stata("SME data 2011.dta")

df2011.head()

/tmp/ipykernel_2661/2373831755.py:3: UnicodeWarning:
One or more strings in the dta file could not be decoded using utf-8, and
so the fallback encoding of latin-1 is being used.  This can happen when a file
has been incorrectly encoded by Stata or some other software. You should verify
the string values returned are correct.
  df2011 = pd.read_stata("SME data 2011.dta")

,q1_11,q2b_11,q2c_11,q2d_11a,q2d_11,q3bd_11,q3bd1_11,q3be_11,q3d_11,q3ea_11,...,qEAir10,qEAjkr10,qEAlr10,qEAinetr10,qEAqur10,qEAvr10,qEAyr10,qEAzr10,id,year
0,4.0,manager,Female,1984.0,27.0,§èng §a,6.0,Ha Noi,Yes,Yes,...,696.000122,42.000000,34.0,620.000122,5480.000000,780.0,0.0,0.0,4.0,2011.0
1,5.0,manager,Female,1985.0,26.0,§èng §a,6.0,Ha Noi,Yes,Yes,...,208.000092,43.200001,17.5,147.300095,8615.000000,1100.0,0.0,0.0,5.0,2011.0
2,14.0,manager,Male,1975.0,36.0,tõ liªm,19.0,Ha Noi,Yes,Yes,...,665.500000,200.000000,78.0,387.500000,20050.900391,930.0,0.0,0.0,14.0,2011.0
3,24.0,manager,Female,1980.0,31.0,®èng ®a,6.0,Ha Noi,Yes,Yes,...,417.999878,14.670000,47.0,356.329865,5200.000000,0.0,0.0,0.0,24.0,2011.0
4,39.0,owner,Male,1952.0,59.0,øng ho¸,281.0,Ha Tay,No,No,...,189.480042,17.280001,0.0,172.200043,905.500000,80.0,0.0,0.0,39.0,2011.0

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving SME data 2015.dta to SME data 2015.dta
Saving SME data 2013.dta to SME data 2013.dta

In [ ]:
import pandas as pd

df2013 = pd.read_stata("SME data 2013.dta")

/tmp/ipykernel_2661/1818323822.py:3: UnicodeWarning:
One or more strings in the dta file could not be decoded using utf-8, and
so the fallback encoding of latin-1 is being used.  This can happen when a file
has been incorrectly encoded by Stata or some other software. You should verify
the string values returned are correct.
  df2013 = pd.read_stata("SME data 2013.dta")

In [ ]:
df2013.head()

,q1_13,q2b_13,q2c_13,q2d_13a,q2d_13,q3bd_13,q3bd1_13,q3be_13,q3d_13,q3ea_13,...,EAq1ir12,EAq1jkr12,EAq1lr12,EAq1inetr12,EAq1qur12,EAq1vr12,EAq1yr12,EAq1zr12,year,id
0,4.0,manager,Female,1973.0,40.0,®èng ®a,6.0,Ha Noi,Yes,Yes,...,NaN,NaN,113.011147,NaN,17174.720703,NaN,NaN,NaN,2013.0,4.0
1,5.0,manager,Female,1985.0,28.0,®èng ®a,6.0,Ha Noi,Yes,Yes,...,294.423767,NaN,111.524162,182.899597,4839.405273,NaN,NaN,NaN,2013.0,5.0
2,14.0,manager,Male,1975.0,38.0,tõ liªm,19.0,Ha Noi,Yes,Yes,...,1402.379028,148.698883,505.150177,748.529968,12763.568359,171.003708,NaN,NaN,2013.0,14.0
3,24.0,manager,Female,1983.0,30.0,®èng ®a,6.0,Ha Noi,Yes,Yes,...,1220.817627,89.219330,1422.304810,-290.706482,6931.598145,594.795532,NaN,NaN,2013.0,24.0
4,39.0,owner,Male,1952.0,61.0,øng Hßa,281.0,Ha Tay,No,No,...,358.289886,NaN,NaN,358.289886,648.327148,NaN,NaN,NaN,2013.0,39.0

In [ ]:
reader = pd.read_stata(
    "SME data 2013.dta",
    iterator=True
)

labels = reader.variable_labels()

NameError: name 'pd' is not defined

In [ ]:
label_df_2013 = pd.DataFrame({
    "Variable": list(labels.keys()),
    "Description": list(labels.values())
})

In [ ]:
label_df_2013.head()

  Variable                  Description
0    q1_13                      Firm id
1   q2b_13       Position of respondent
2   q2c_13         Gender of respondent
3  q2d_13a  Year of birth of respondent
4   q2d_13            Age of respondent

In [ ]:
label_df_2013.to_excel(
    "Variable_Labels_2013.xlsx",
    index=False
)

In [ ]:
files.download(
    "Variable_Labels_2013.xlsx"
)

In [ ]:
df2015 = pd.read_stata(
    "SME data 2015.dta"
)

/tmp/ipykernel_2661/487255707.py:1: UnicodeWarning:
One or more strings in the dta file could not be decoded using utf-8, and
so the fallback encoding of latin-1 is being used.  This can happen when a file
has been incorrectly encoded by Stata or some other software. You should verify
the string values returned are correct.
  df2015 = pd.read_stata(

In [ ]:
reader = pd.read_stata(
    "SME data 2015.dta",
    iterator=True
)

labels = reader.variable_labels()

In [ ]:
label_df_2015 = pd.DataFrame({
    "Variable": list(labels.keys()),
    "Description": list(labels.values())
})

In [ ]:
label_df_2015.to_excel(
    "Variable_Labels_2015.xlsx",
    index=False
)

In [ ]:
files.download(
    "Variable_Labels_2015.xlsx"
)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

os.listdir('/content/drive/MyDrive/SME_Project')

['kinh tế lượng ứng dụng',
 'SME_data_2011.xlsx',
 'SME_data_2013.xlsx',
 'SME_data_2015.xlsx',
 'Variable_Labels_2011.xlsx',
 'Variable_Labels_2013.xlsx',
 'Variable_Labels_2015.xlsx',
 'SME-project',
 'Tài liệu không có tiêu đề.gdoc']

In [ ]:
import pandas as pd

df2011 = pd.read_excel(
    '/content/drive/MyDrive/SME_project/SME_data_2011.xlsx'
)

df2013 = pd.read_excel(
    '/content/drive/MyDrive/SME_project/SME_data_2013.xlsx'
)

df2015 = pd.read_excel(
    '/content/drive/MyDrive/SME_project/SME_data_2015.xlsx'
)

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/SME_project/SME_data_2011.xlsx'

In [ ]:
import os

print(os.path.exists('/content/drive'))
print(os.path.exists('/content/drive/MyDrive'))

True
True

In [ ]:
import os

print(os.listdir('/content/drive/MyDrive'))

['SME_Project', 'Cambridge 17 Bản Đẹp.pdf', 'IMG_4805.JPG', 'IMG_4806.JPG', 'Ktpt', 'Đào Trang Newbie.JPG', 'Trang', 'Bản sao của Đào Thị Thu Tranh- Content intern.pdf', 'Đào Thị Thu Tranh- Content intern.pdf', 'Đào Thị Thu Trang- Vị trí ứng tuyển Content Creator.pdf', 'CV-Content Creative Intern-Đào Thị Thu Trang.pdf', 'Sự kiện - Đào Thị Thu Trang.pdf', 'Đào Thị Thu Trang.gsheet', 'ĐÁNH GIÁ THÀNH VIÊN.gsheet', 'câu 2.gdoc', 'IMG_4973.JPG', 'Đào Thị Thu Trang.docx', 'Đào Thị Thu Trang.pdf', 'IMG_6318.HEIC', 'IMG_6319.HEIC', 'IMG_6321.HEIC', 'IMG_6327.HEIC', 'IMG_6328.HEIC', 'IMG_6325.HEIC', 'IMG_6324.HEIC', 'IMG_6320.HEIC', 'IMG_6326.HEIC', 'IMG_6322.MOV', 'IMG_6323.MOV', 'Causes.gdoc', 'IMG_9708.JPG', 'IMG_9699.JPG', 'IMG_9701.JPG', 'IMG_9697.JPG', 'IMG_5304.heif', 'IMG_5306.heif', 'IMG_5305.heif', 'IMG_5308.heif', 'Ch%C6%B0%C6%A1ng%204-THUDTQLKT.xlsx', 'CV- Đào Thị Thu Trang.gdoc', 'Đào Thị Thu Trang- core team gen 15.JPG', 'em để ueb visa ở quê rồi ạ.gdoc', 'IMG_8232.HEIC', 'IMG_8233.HEIC', 'IMG_8212.MOV', 'IMG_8228.MOV', 'IMG_8209.MOV', 'IMG_8211.MOV', 'IMG_8210.MOV', 'IMG_8238.MOV', 'IMG_8369.MOV', '1IE3SFNEK_8227TC.mp4', 'IMG_8204.MOV', 'IMG_8245.PNG', 'IMG_8244.PNG', 'IMG_8203.MOV', 'IMG_8207.MOV', 'IMG_8237.MOV', 'IMG_8235.MOV', 'IMG_8334.MOV', 'IMG_8229.MOV', 'IMG_8231.MOV', 'IMG_8208.MOV', 'IMG_8234.MOV', 'IMG_8230.MOV', 'IMG_8333.MOV', 'IMG_8236.MOV', 'Nhảy sạp.mov', 'Cuisine.mov', 'ACKNOWLEDGMENTS.gdoc', 'copy_E42BAA16-63D9-43F4-A13C-053F91A4E61F.mov', 'Discussion week 2 team 5.gdoc', 'câu 1: .gdoc', 'Câu 1 (1).gdoc', 'Danh sách việc cần làm.gsheet', '51. Đào Thị Thu Trang -23050645 (1)', 'Galaxy campus friends mùa 2.gdoc', 'Nhóm 2, QH2023E-KTPT3.pdf', 'quizz kdqt 10 câu.gdoc', 'Tài liệu không có tiêu đề (8).gdoc', '51. Đào Thị Thu Trang -23050645', 'Huế.gsheet', 'Đào Thị Thu Trang - Vị trí ứng tuyển TTS Nhập liệu hồ sơ.pdf', 'Đào Thị Thu Trang - Vị trí ứng tuyển TTS Nhập liệu hồ sơ.jpg', 'Công việc', 'bằng tiếng anh.gsheet', 'CÂU TRẢ LỜI ÔN TẬP THI VIẾT MÔN LÝ LUẬN NHÀ NƯỚC VÀ PHÁP LUẬT 2024 - Biểu đồ dạng đường 1.gsheet', 'CÂU TRẢ LỜI ÔN TẬP THI VIẾT MÔN LÝ LUẬN NHÀ NƯỚC VÀ PHÁP LUẬT 2024 (1).pdf', 'CÂU TRẢ LỜI ÔN TẬP THI VIẾT MÔN LÝ LUẬN NHÀ NƯỚC VÀ PHÁP LUẬT 2024.pdf', 'từ tài liệu này, hãy giúp tôi hoàn thành phần thà....gsheet', 'Ghi chú cuộc họp.gdoc', 'Sơ yếu lý lịch.gdoc', 'Môn tiếng anh', 'Anh lớp 5.gdoc', 'LOOK5', 'NHÓM 3 - TÀI LIỆU THAM KHẢO.gdoc', 'Kthptbbv.gdoc', '3.pdf', 'CÂU HỎI ÔN THI HỌC PHẦN LỊCH SỬ NHÀ NƯỚC VÀ PHÁP LUẬT 2024.gdoc', 'Tài liệu không có tiêu đề (7).gdoc', 'BẢNG HỎI NCKH.gdoc', 'NCKH', 'Tài liệu không có tiêu đề (6).gdoc', 'idea.gdoc', 'KỊCH BẢN TMĐT.gsheet', 'Tài liệu không có tiêu đề (5).gdoc', 'Teal and White Modern Building Project Proposal Presentation.pdf.pdf', 'Đào.gdoc', 'Tài liệu không có tiêu đề (4).gdoc', 'BRIEF BVS MÂY HỒNG - CỎ MỀM.gsheet', 'Tài liệu không có tiêu đề (3).gdoc', 'Tài liệu không có tiêu đề (2).gdoc', 'CÂU 2: Trình bày các giải pháp thường sử dụng để phát triển hệ thống Tài chính.gdoc', 'Câu 1.gdoc', '%C4%90E%CC%82%CC%80%20CU%CC%9BO%CC%9BNG%20TCPT.docx', 'Tài liệu không có tiêu đề (1).gdoc', '23050384-Lê Quỳnh An TMĐT FINAL EXAM (1).pdf', 'Tài liệu không có tiêu đề.gdoc', 'Câu hỏi_LSNNPL_Lớp LKD.doc', 'Colab Notebooks', 'Thông tin.gsheet', 'The concept of the sharing economy has increasingly been applied in agricultural systems as a mechanism to enhance resource ~, and promote sustainable development in rural areas (Miralles, Dentoni, & Pascucci, 2017; Rodrigues, Franco, & Silva, 2021).gdoc', 'Background:-> Gap ( chưa ai làm mô hình này ở Điện Biên)- Methoth ( TAM,TPB).gdoc', 'BẢNG 1.gdoc', 'Mô hình nhị phân (Binary model) là một loại mô hình thống kê hoặc kinh tế lượng được sử dụng khi biến phụ thuộc (dependent variable) chỉ có hai trạng thái hoặc hai kết quả.gdoc', 'Background for the sharing economy models in agriculture.gdoc', 'trag.gsheet', 'Giá cả 1.gsheet', 'result (1).gdoc', '2.gdoc', 'result.gdoc', 'SUPERMARKET WORKFLOW.gsheet', 'PHẦN III – KẾT QUẢ NGHIÊN CỨU.gdoc', 'RESULT PLS SEM.gdoc', 'ván gỗ.gsheet', 'chè 1.xlsx', 'BT chè.gsheet', 'cccd', '15.12.2024 ĐC QLNN KT Không ĐA-gửi SV.docx', 'học chat', 'HỌC DA.gdoc', 'Bảng tính không có tiêu đề (1).gsheet', 'LUẬT -VNU', 'mô hình ra quyết định', 'KTLUD.gdoc', 'ĐÀO THỊ THU TRANG - CV DATA ANALYST INTERN.gdoc', 'ĐÀO THỊ THU TRANG - CV DATA ANALYST INTERN V2.gdoc', 'ĐÀO THỊ THU TRANG - CV DATA ANALYST INTERN V3.gdoc', 'ĐÀO THỊ THU TRANG - CV DATA ANALYST INTERN V4.gdoc', 'ĐÀO THỊ THU TRANG - CV DATA ANALYST INTERN V3 cải tiến.gdoc', 'Kịch bản Video Intro - Tiến trình hình thành học thuyết kinh tế Karl Marx.gsheet', 'Tăng trưởng xanh.gdoc', 'Để phân vai thật hợp lý và "chuẩn chỉnh" cho nhóm 5 người dựa trên kịch bản Tiến trình hình th~nhân sự cần phải kết hợp linh hoạt giữa Diễn viên (On-camera) và Ê-kíp sản xuất (Behind the scenes).gdoc', '114632-V1 (2).zip', 'Bảng tính không có tiêu đề.gsheet']

In [ ]:
import os

for item in os.listdir('/content/drive/MyDrive'):
    print(repr(item))

'SME_Project'
'Cambridge 17 Bản Đẹp.pdf'
'IMG_4805.JPG'
'IMG_4806.JPG'
'Ktpt'
'Đào Trang Newbie.JPG'
'Trang'
'Bản sao của Đào Thị Thu Tranh- Content intern.pdf'
'Đào Thị Thu Tranh- Content intern.pdf'
'Đào Thị Thu Trang- Vị trí ứng tuyển Content Creator.pdf'
'CV-Content Creative Intern-Đào Thị Thu Trang.pdf'
'Sự kiện - Đào Thị Thu Trang.pdf'
'Đào Thị Thu Trang.gsheet'
'ĐÁNH GIÁ THÀNH VIÊN.gsheet'
'câu 2.gdoc'
'IMG_4973.JPG'
'Đào Thị Thu Trang.docx'
'Đào Thị Thu Trang.pdf'
'IMG_6318.HEIC'
'IMG_6319.HEIC'
'IMG_6321.HEIC'
'IMG_6327.HEIC'
'IMG_6328.HEIC'
'IMG_6325.HEIC'
'IMG_6324.HEIC'
'IMG_6320.HEIC'
'IMG_6326.HEIC'
'IMG_6322.MOV'
'IMG_6323.MOV'
'Causes.gdoc'
'IMG_9708.JPG'
'IMG_9699.JPG'
'IMG_9701.JPG'
'IMG_9697.JPG'
'IMG_5304.heif'
'IMG_5306.heif'
'IMG_5305.heif'
'IMG_5308.heif'
'Ch%C6%B0%C6%A1ng%204-THUDTQLKT.xlsx'
'CV- Đào Thị Thu Trang.gdoc'
'Đào Thị Thu Trang- core team gen 15.JPG'
'em để ueb visa ở quê rồi ạ.gdoc'
'IMG_8232.HEIC'
'IMG_8233.HEIC'
'IMG_8212.MOV'
'IMG_8228.MOV'
'IMG_8209.MOV'
'IMG_8211.MOV'
'IMG_8210.MOV'
'IMG_8238.MOV'
'IMG_8369.MOV'
'1IE3SFNEK_8227TC.mp4'
'IMG_8204.MOV'
'IMG_8245.PNG'
'IMG_8244.PNG'
'IMG_8203.MOV'
'IMG_8207.MOV'
'IMG_8237.MOV'
'IMG_8235.MOV'
'IMG_8334.MOV'
'IMG_8229.MOV'
'IMG_8231.MOV'
'IMG_8208.MOV'
'IMG_8234.MOV'
'IMG_8230.MOV'
'IMG_8333.MOV'
'IMG_8236.MOV'
'Nhảy sạp.mov'
'Cuisine.mov'
'ACKNOWLEDGMENTS.gdoc'
'copy_E42BAA16-63D9-43F4-A13C-053F91A4E61F.mov'
'Discussion week 2 team 5.gdoc'
'câu 1: .gdoc'
'Câu 1 (1).gdoc'
'Danh sách việc cần làm.gsheet'
'51. Đào Thị Thu Trang -23050645 (1)'
'Galaxy campus friends mùa 2.gdoc'
'Nhóm 2, QH2023E-KTPT3.pdf'
'quizz kdqt 10 câu.gdoc'
'Tài liệu không có tiêu đề (8).gdoc'
'51. Đào Thị Thu Trang -23050645'
'Huế.gsheet'
'Đào Thị Thu Trang - Vị trí ứng tuyển TTS Nhập liệu hồ sơ.pdf'
'Đào Thị Thu Trang - Vị trí ứng tuyển TTS Nhập liệu hồ sơ.jpg'
'Công việc'
'bằng tiếng anh.gsheet'
'CÂU TRẢ LỜI ÔN TẬP THI VIẾT MÔN LÝ LUẬN NHÀ NƯỚC VÀ PHÁP LUẬT 2024 - Biểu đồ dạng đường 1.gsheet'
'CÂU TRẢ LỜI ÔN TẬP THI VIẾT MÔN LÝ LUẬN NHÀ NƯỚC VÀ PHÁP LUẬT 2024 (1).pdf'
'CÂU TRẢ LỜI ÔN TẬP THI VIẾT MÔN LÝ LUẬN NHÀ NƯỚC VÀ PHÁP LUẬT 2024.pdf'
'từ tài liệu này, hãy giúp tôi hoàn thành phần thà....gsheet'
'Ghi chú cuộc họp.gdoc'
'Sơ yếu lý lịch.gdoc'
'Môn tiếng anh'
'Anh lớp 5.gdoc'
'LOOK5'
'NHÓM 3 - TÀI LIỆU THAM KHẢO.gdoc'
'Kthptbbv.gdoc'
'3.pdf'
'CÂU HỎI ÔN THI HỌC PHẦN LỊCH SỬ NHÀ NƯỚC VÀ PHÁP LUẬT 2024.gdoc'
'Tài liệu không có tiêu đề (7).gdoc'
'BẢNG HỎI NCKH.gdoc'
'NCKH'
'Tài liệu không có tiêu đề (6).gdoc'
'idea.gdoc'
'KỊCH BẢN TMĐT.gsheet'
'Tài liệu không có tiêu đề (5).gdoc'
'Teal and White Modern Building Project Proposal Presentation.pdf.pdf'
'Đào.gdoc'
'Tài liệu không có tiêu đề (4).gdoc'
'BRIEF BVS MÂY HỒNG - CỎ MỀM.gsheet'
'Tài liệu không có tiêu đề (3).gdoc'
'Tài liệu không có tiêu đề (2).gdoc'
'CÂU 2: Trình bày các giải pháp thường sử dụng để phát triển hệ thống Tài chính.gdoc'
'Câu 1.gdoc'
'%C4%90E%CC%82%CC%80%20CU%CC%9BO%CC%9BNG%20TCPT.docx'
'Tài liệu không có tiêu đề (1).gdoc'
'23050384-Lê Quỳnh An TMĐT FINAL EXAM (1).pdf'
'Tài liệu không có tiêu đề.gdoc'
'Câu hỏi_LSNNPL_Lớp LKD.doc'
'Colab Notebooks'
'Thông tin.gsheet'
'The concept of the sharing economy has increasingly been applied in agricultural systems as a mechanism to enhance resource ~, and promote sustainable development in rural areas (Miralles, Dentoni, & Pascucci, 2017; Rodrigues, Franco, & Silva, 2021).gdoc'
'Background:-> Gap ( chưa ai làm mô hình này ở Điện Biên)- Methoth ( TAM,TPB).gdoc'
'BẢNG 1.gdoc'
'Mô hình nhị phân (Binary model) là một loại mô hình thống kê hoặc kinh tế lượng được sử dụng khi biến phụ thuộc (dependent variable) chỉ có hai trạng thái hoặc hai kết quả.gdoc'
'Background for the sharing economy models in agriculture.gdoc'
'trag.gsheet'
'Giá cả 1.gsheet'
'result (1).gdoc'
'2.gdoc'
'result.gdoc'
'SUPERMARKET WORKFLOW.gsheet'
'PHẦN III – KẾT QUẢ NGHIÊN CỨU.gdoc'
'RESULT PLS SEM.gdoc'
'ván gỗ.gsheet'
'chè 1.xlsx'
'BT chè.gsheet'
'cccd'
'15.12.2024 ĐC QLNN KT Không ĐA-gửi SV.docx'
'học chat'
'HỌC DA.gdoc'
'Bảng tính không có tiêu đề (1).gsheet'
'LUẬT -VNU'
'mô hình ra quyết định'
'KTLUD.gdoc'
'ĐÀO THỊ THU TRANG - CV DATA ANALYST INTERN.gdoc'
'ĐÀO THỊ THU TRANG - CV DATA ANALYST INTERN V2.gdoc'
'ĐÀO THỊ THU TRANG - CV DATA ANALYST INTERN V3.gdoc'
'ĐÀO THỊ THU TRANG - CV DATA ANALYST INTERN V4.gdoc'
'ĐÀO THỊ THU TRANG - CV DATA ANALYST INTERN V3 cải tiến.gdoc'
'Kịch bản Video Intro - Tiến trình hình thành học thuyết kinh tế Karl Marx.gsheet'
'Tăng trưởng xanh.gdoc'
'Để phân vai thật hợp lý và "chuẩn chỉnh" cho nhóm 5 người dựa trên kịch bản Tiến trình hình th~nhân sự cần phải kết hợp linh hoạt giữa Diễn viên (On-camera) và Ê-kíp sản xuất (Behind the scenes).gdoc'
'114632-V1 (2).zip'
'Bảng tính không có tiêu đề.gsheet'

In [ ]:
import os

for root, dirs, files in os.walk('/content/drive/MyDrive'):
    for f in files:
        if 'SME_data_2011' in f:
            print(os.path.join(root, f))

/content/drive/MyDrive/SME_Project/SME_data_2011.xlsx

In [ ]:
import pandas as pd

df2011 = pd.read_excel(
    '/content/drive/MyDrive/SME_Project/SME_data_2011.xlsx'
)

df2013 = pd.read_excel(
    '/content/drive/MyDrive/SME_Project/SME_data_2013.xlsx'
)

df2015 = pd.read_excel(
    '/content/drive/MyDrive/SME_Project/SME_data_2015.xlsx'
)

print("Đọc dữ liệu thành công")

Đọc dữ liệu thành công

In [ ]:
labels2011 = pd.read_excel(
    '/content/drive/MyDrive/SME_Project/Variable_Labels_2011.xlsx'
)

labels2013 = pd.read_excel(
    '/content/drive/MyDrive/SME_Project/Variable_Labels_2013.xlsx'
)

labels2015 = pd.read_excel(
    '/content/drive/MyDrive/SME_Project/Variable_Labels_2015.xlsx'
)

In [ ]:
labels2011[
    labels2011['Description']
    .str.contains(
        'net profit',
        case=False,
        na=False
    )
]

       Variable                                     Description
699   qEAinet09            Total net profits 2009 (million VND)
700   qEAinet10            Total net profits 2010 (million VND)
722  qEAinetr09  Real total net profits 2009 (million 2010 VND)
736  qEAinetr10  Real total net profits 2010 (million 2010 VND)

In [ ]:
labels2013[
    labels2013['Description']
    .str.contains(
        'net profit',
        case=False,
        na=False
    )
]

        Variable                                     Description
794   EAq1inet11            Total net profits 2011 (million VND)
795   EAq1inet12            Total net profits 2012 (million VND)
823  EAq1inetr11  Real total net profits 2011 (million 2010 VND)
843  EAq1inetr12  Real total net profits 2012 (million 2010 VND)

In [ ]:
labels2015[
    labels2015['Description']
    .str.contains(
        'net profit',
        case=False,
        na=False
    )
]

        Variable                                Description
748  EAq1enet_13       Total net profits 2013 (million VND)
749  EAq1enet_14       Total net profits 2014 (million VND)
762  EAq1enetr13  Real total net profits 2013 (million VND)
774  EAq1enetr14  Real total net profits 2014 (million VND)

In [ ]:
labels2011[
    labels2011['Description']
    .str.contains(
        'credit|loan|debt',
        case=False,
        na=False
    )
]

      Variable                                        Description
305   q71b2_11              Borrowed from bank/credit institution
321   q73bb_11                  Outstanding credits (million VND)
331    q75a_11          Formal short term debt 2010 (million VND)
332    q75b_11        Informal short term debt 2010 (million VND)
333    q75c_11            Formal long term debt 2010(million VND)
334    q75d_11         Informal long term debt 2010 (million VND)
336    q76a_11  Interest payment on formal loans in 2010 (mill...
337     q77_11        Firm failed to service debt on time in 2010
338    q77a_11  Number of times failed to service debt on time...
344     q80_11           Firm applied for formal loans since 2009
345     q81_11                          Problems getting the loan
346    q81a_11            Causes of problems for getting the loan
347     q82_11       Number of formal loans (short and long term)
348    q82a_11                  Number of formal short term loans
349    q82b_11                   Number of formal long term loans
350     q83_11  Which bank/formal credit institution do you pr...
351    q84a_11      Number of formal short term loan applications
352    q84b_11       Number of formal long term loan applications
353    q85a_11   Source of the most important current formal loan
354    q85b_11  Amount originally borrowed (million VND) for f...
357   q85c1_11                      Duration of the loan (months)
358    q85d_11    Current liability (million VND) for formal loan
359    q85e_11             Interest rate, % month for formal loan
360    q85f_11      Assets required as collateral for formal loan
361   q85fa_11                Types of collateral for formal loan
362    q85g_11                      Guarantor for the formal loan
364     q86_11                               Need additional loan
365    q86a_11                                Why additional loan
366    q86b_11                            Why not additional loan
367     q87_11    Why have not applied for formal loan since 2009
370    q88b_11  Number of informal long term loans since Augus...
371    q88c_11          Difficulties in obtaining informal credit
372   q88ca_11  How many times had difficulties in obtaining i...
373    q89a_11                            Source of informal loan
374    q89b_11  Amount originally borrowed (million VND) for i...
375   q89ca_11                     Duration of this loan (months)
376    q89d_11  Current liability (million VND) for informal loan
377    q89e_11           Interest rate, % month for informal loan
379   q89fa_11              Types of collateral for informal loan
380    q89g_11                    Guarantor for the informal loan
381   q89ga_11  Relationship with the guarantor for the inform...
382     q90_11           Most important type of loan for the firm
383     q91_11       Distance to the most important creditor (km)
384     q92_11                                Creditor's location
385     q93_11        Firm ever given a loan to the main creditor
386     q94_11               Firm borrowed from the main creditor
575   q118c_11                 Number of contacts who are debtors
576   q118d_11               Number of contacts who are creditors
622  q128b2_11  Received government assistance in 2010 for VDB...
628  q128c2_11  Administrative level of assistance for VDB of ...
634  q128d2_11  How did you get in contact with the authoritie...
641  q128e2_11                        Bribe for VDB of VBSP loans
647  q128f2_11                    The impact of VDB of VBSP loans
703     qEAv09          Total outstanding debt 2009 (million VND)
704     qEAv10          Total outstanding debt 2010 (million VND)
724    qEAvr09  Real total outstanding debt 2009 (million 2010...
738    qEAvr10  Real total outstanding debt 2010 (million 2010...

In [ ]:
labels2013[
    labels2013['Description']
    .str.contains(
        'credit|loan|debt',
        case=False,
        na=False
    )
]

      Variable                                        Description
310   q71b2_13              Borrowed from bank/credit institution
326   q73bb_13                  Outstanding credits (million VND)
336    q75a_13          Formal short term debt 2012 (million VND)
337    q75b_13        Informal short term debt 2012 (million VND)
338    q75c_13            Formal long term debt 2012(million VND)
339    q75d_13         Informal long term debt 2012 (million VND)
341    q76a_13  Interest payment on formal loans in 2012 (mill...
342     q77_13        Firm failed to service debt on time in 2012
343    q77a_13  Number of times failed to service debt on time...
349     q80_13           Firm applied for formal loans since 2011
350     q81_13                          Problems getting the loan
351    q81a_13            Causes of problems for getting the loan
352     q82_13       Number of formal loans (short and long term)
353    q82a_13                  Number of formal short term loans
354    q82b_13                   Number of formal long term loans
355    q83a_13  Which bank/formal credit institution do you pr...
356    q84a_13      Number of formal short term loan applications
357    q84b_13       Number of formal long term loan applications
358    q85a_13   Source of the most important current formal loan
359    q85b_13  Amount originally borrowed (million VND) for f...
362   q85c1_13                      Duration of the loan (months)
363    q85d_13    Current liability (million VND) for formal loan
364    q85e_13             Interest rate, % month for formal loan
365    q85f_13      Assets required as collateral for formal loan
366   q85fa_13                Types of collateral for formal loan
367    q85g_13                      Guarantor for the formal loan
369     q86_13                               Need additional loan
370    q86a_13                                Why additional loan
371    q86b_13                            Why not additional loan
372     q87_13    Why have not applied for formal loan since 2011
375    q88b_13  Number of informal long term loans since Augus...
376    q88c_13          Difficulties in obtaining informal credit
377   q88ca_13  How many times had difficulties in obtaining i...
378    q89a_13                            Source of informal loan
379    q89b_13  Amount originally borrowed (million VND) for i...
380   q89ca_13                     Duration of this loan (months)
381    q89d_13  Current liability (million VND) for informal loan
382    q89e_13           Interest rate, % month for informal loan
384   q89fa_13              Types of collateral for informal loan
385    q89g_13                    Guarantor for the informal loan
386   q89ga_13  Relationship with the guarantor for the inform...
387     q90_13           Most important type of loan for the firm
388     q91_13       Distance to the most important creditor (km)
389     q92_13                                Creditor's location
390     q93_13        Firm ever given a loan to the main creditor
391     q94_13               Firm borrowed from the main creditor
630   q118c_13                 Number of contacts who are debtors
631   q118d_13               Number of contacts who are creditors
699  q128b2_13  Received government assistance in 2012 for VDB...
705  q128c2_13  Administrative level of assistance for VDB of ...
711  q128d2_13  How did you get in contact with the authoritie...
718  q128e2_13                        Bribe for VDB of VBSP loans
724  q128f2_13                    The impact of VDB of VBSP loans
730  q128g2_13      Would like to have received VDB of VBSP loans
798    EAq1v11          Total outstanding debt 2011 (million VND)
799    EAq1v12          Total outstanding debt 2012 (million VND)
825   EAq1vr11  Real total outstanding debt 2011 (million 2010...
845   EAq1vr12  Real total outstanding debt 2012 (million 2010...

In [ ]:
labels2015[
    labels2015['Description']
    .str.contains(
        'credit|loan|debt',
        case=False,
        na=False
    )
]

      Variable                                        Description
78     q22b_15                          Loans from family members
79     q22c_15               Loans from friends and acquaintances
80     q22d_15                        Loans from local government
81     q22e_15                                 Domestic bank loan
82     q22f_15                            International bank loan
83     q22g_15  Informal credit association (money lenders, in...
277   q63b2_15              Borrowed from bank/credit institution
293   q65bb_15                  Outstanding credits (million VND)
297    q67a_15  Interest payment on formal loans in 2014 (mill...
298     q68_15        Firm failed to service debt on time in 2014
300     q70_15           Firm applied for formal loans since 2013
301     q71_15                          Problems getting the loan
302    q71a_15            Causes of problems for getting the loan
303     q72_15       Number of formal loans (short and long term)
304    q72a_15                  Number of formal short term loans
305    q72b_15                   Number of formal long term loans
306    q73a_15  Which bank/formal credit institution do you pr...
307     q74_15  Number of formal loan applications (short and ...
308    q74a_15      Number of formal short term loan applications
309    q74b_15       Number of formal long term loan applications
310    q75a_15   Source of the most important current formal loan
311    q75b_15  Amount originally borrowed (million VND) for f...
314   q75c1_15                      Duration of the loan (months)
315    q75d_15    Current liability (million VND) for formal loan
316    q75e_15             Interest rate, % month for formal loan
317    q75f_15      Assets required as collateral for formal loan
318   q75fa_15                Types of collateral for formal loan
319    q75g_15                      Guarantor for the formal loan
321     q76_15                               Need additional loan
322    q76a_15                                Why additional loan
323    q76b_15                            Why not additional loan
324     q77_15    Why have not applied for formal loan since 2013
327    q78b_15  Number of informal long term loans since Augus...
328    q78c_15          Difficulties in obtaining informal credit
329   q78ca_15  How many times had difficulties in obtaining i...
330    q79a_15                            Source of informal loan
331    q79b_15  Amount originally borrowed (million VND) for i...
332   q79ca_15                     Duration of this loan (months)
333    q79d_15  Current liability (million VND) for informal loan
334    q79e_15           Interest rate, % month for informal loan
336   q79fa_15              Types of collateral for informal loan
337    q79g_15                    Guarantor for the informal loan
338   q79ga_15  Relationship with the guarantor for the inform...
339     q80_15           Most important type of loan for the firm
340     q81_15       Distance to the most important creditor (km)
341     q82_15                                Creditor's location
342     q83_15        Firm ever given a loan to the main creditor
343     q84_15               Firm borrowed from the main creditor
563   q110c_15                   Number of contacts among debtors
564   q110d_15                 Number of contacts among creditors
651  q126da_15                Did you receive a bank loan in 2009
652  q126db_15      Loan obtained under the 2009 stimulus package
653  q126dc_15  The amount of the loan under the 2009 stimulus...
654  q126dd_15  Interest rate on the loan under the 2009 stimu...
742   EAq1i_13  Total outstanding debt, end-year 2013 (million...
743   EAq1i_14  Total outstanding debt, end-year 2014 (million...
760   EAq1ir13  Real total outstanding debt 2013 (million 2010...
772   EAq1ir14  Real total outstanding debt 2014 (million 2010...

In [ ]:
labels2011[
    labels2011['Description']
    .str.contains(
        'total assets',
        case=False,
        na=False
    )
]

      Variable                                Description
322  tot_ass11      Total assets 2010 (million VND) value
701    qEAqu09            Total assets 2009 (million VND)
702    qEAqu10            Total assets 2010 (million VND)
723   qEAqur09  Real total assets 2009 (million 2010 VND)
737   qEAqur10  Real total assets 2010 (million 2010 VND)

In [ ]:
labels2013[
    labels2013['Description']
    .str.contains(
        'total assets',
        case=False,
        na=False
    )
]

      Variable                                Description
327  tot_ass13      Total assets 2012 (million VND) value
796   EAq1qu11            Total assets 2011 (million VND)
797   EAq1qu12            Total assets 2012 (million VND)
824  EAq1qur11  Real total assets 2011 (million 2010 VND)
844  EAq1qur12  Real total assets 2012 (million 2010 VND)

In [ ]:
labels2015[
    labels2015['Description']
    .str.contains(
        'total assets',
        case=False,
        na=False
    )
]

      Variable                                        Description
294  tot_ass15              Total assets 2015 (million VND) value
740   EAq1h_13  Total assets, end-year 2013 (million VND), nom...
741   EAq1h_14  Total assets, end-year 2014 (million VND), nom...
759   EAq1hr13          Real total assets 2013 (million 2010 VND)
771   EAq1hr14          Real total assets 2014 (million 2010 VND)

In [ ]:
labels2011[
    labels2011['Description']
    .str.contains(
        'labour|labor|employee',
        case=False,
        na=False
    )
]

          Variable                                        Description
61         q20i_11                              Lack of skilled labor
408        q100_11  Number of full-time employees at the time of e...
409     q101aaa_11  Firm size (number of full-time regular employees)
410      q101a1_11                                 Total labour force
411     q101abt_11                           Total casual labor force
412       q101b_11                          Share unpaid labour force
413      q101a2_11                Share regular labour force of total
414      q101a4_11                 Share casual labour force of total
415       q101c_11  Percentage of regular full-time labour force w...
416      q101da_11  Percentage of regular full-time labour force w...
417      q101db_11  Percentage of regular full-time labour with co...
418      q101dc_11  Percentage of regular full-time labour with co...
419      q101dd_11  Percentage of regular full-time labour force w...
420  contract3M_11  Percentage of regular full-time labour force w...
421       q101e_11  Average number of days worked per month by a r...
422       q101f_11  hours worked per day by a regular full-time em...
446     q102tff_11                               Labourer (unskilled)
463     q102wff_11                        Labourer (unskilled), women
465       q103a_11              Number of new employees hired in 2010
479       q103c_11       Did the firm reduce its labour force in 2010
480       q103d_11  Reason for firm reducing its labour force in 2010
481       q103e_11  Informing employees/representative organizatio...
500       q109g_11  Are employees paid overtime for working outsid...
508      q111ad_11  Does the enterprise have a Collective Labour A...
509       q111b_11  Has the enterprise had any labour dispute the ...
512       q112c_11  Did you pay contribution to unemployment insur...
520       q114b_11  Do you rely on measures to ensure that your em...
668     q130b03_11                                        Labour code
677       q131a_11  Times inspected by policy compliance inspectio...
705         qEAx09           Total number of full-time employees 2009
706         qEAx10           Total number of full-time employees 2010

In [ ]:
labels2013[
    labels2013['Description']
    .str.contains(
        'labour|labor|employee',
        case=False,
        na=False
    )
]

          Variable                                        Description
62         q20i_13                              Lack of skilled labor
414        q100_13  Number of full-time employees at the time of e...
415     q101aaa_13  Firm size (number of full-time regular employees)
416      q101a1_13                                 Total labour force
417     q101abt_13                           Total casual labor force
418       q101b_13                          Share unpaid labour force
419      q101a2_13          Share regular total labour force of total
420      q101a3_13      Share regular full-time labour force of total
421      q101a4_13      Share regular part-time labour force of total
422      q101a5_13                 Share casual labour force of total
423      q101f2_13                          Total female labour force
424     q101f2_13s                          Female labour force share
425       q101c_13  Percentage of regular full-time labour force w...
426      q101da_13  Percentage of regular full-time labour force w...
427      q101db_13  Percentage of regular full-time labour with co...
428      q101dc_13  Percentage of regular full-time labour with co...
429      q101dd_13  Percentage of regular full-time labour force w...
430  contract3M_13  Percentage of regular full-time labour force w...
431       q101e_13  Average number of days worked per month by a r...
432       q101f_13  Hours worked per day by a regular full-time em...
456     q102tff_13                               Labourer (unskilled)
473     q102wff_13                        Labourer (unskilled), women
475       q103a_13              Number of new employees hired in 2012
504       q103c_13  Reason for firm reducing its labour force in 2012
505       q103d_13  Informing employees/representative organizatio...
539       q109g_13  Are employees paid overtime for working outsid...
543     q109hda_13  Time between informing the employee and wage/i...
552      q111ae_13  Does the enterprise have a Collective Labour A...
553     q111ae1_13  When was the most recent Collective Labour Agr...
554     q111ae2_13  Has this Collective Labour Agreement been repo...
555       q111b_13  Has the enterprise had any labour dispute the ...
558       q112c_13  Did you pay contribution to unemployment insur...
566        q114_13  Measures to ensure that your employees work ha...
690      q127c3_13                      Reducing size of labour force
691      q127c4_13  Maintaining size of labour force but reducing ...
751     q130b03_13                                        Labour code
760       q131a_13  Times inspected by policy compliance inspectio...
774        EAq1h11     Nominal average monthly other labor costs 2011
780        EAq1h12     Nominal average monthly other labor costs 2012
800        EAq1x11           Total number of full-time employees 2011
801        EAq1x12           Total number of full-time employees 2012
813       EAq1hr11  Real average monthly other labor costs 2011 (m...
833       EAq1hr12  Real average monthly other labor costs 2012 (m...

In [ ]:
labels2015[
    labels2015['Description']
    .str.contains(
        'labour|labor|employee',
        case=False,
        na=False
    )
]

          Variable                                        Description
63         q20i_15                              Lack of skilled labor
367       q90at_15                                 Total labour force
368      q90aat_15      Regular labor force (full time and part time)
369     q90aaat_15                      Regular full time labor force
370     q90aabt_15                      Regular part time labor force
371      q90abt_15                           Total casual labor force
372     q90b_sh_15                          Share unpaid labour force
373   q90aat_sh_15          Share regular total labour force of total
374  q90aaat_sh_15      Share regular full-time labour force of total
375  q90aabt_sh_15      Share regular part-time labour force of total
376   q90abt_sh_15                 Share casual labour force of total
377       q90af_15                          Total female labour force
378    q90af_sh_15                          Female labour force share
379        q90c_15  Percentage of regular full-time labour force w...
380       q90da_15  Percentage of regular full-time labour force w...
381       q90db_15  Percentage of regular full-time labour with co...
382       q90dc_15  Percentage of regular full-time labour with co...
383       q90dd_15  Percentage of regular full-time labour force w...
384  contract3M_15  Percentage of regular full-time labour force w...
385        q90e_15  Average number of days worked per month by a r...
386        q90f_15  Average number of hours worked per day by a re...
412        q92a_15              Number of new employees hired in 2014
442        q93b_15  Informing employees/representative organizatio...
476       q101g_15  Are employees paid overtime for working outsid...
485      q103ae_15  Does the enterprise have a Collective Labour A...
486     q103ae1_15  When was the most recent Collective Labour Agr...
487     q103ae2_15  Has this Collective Labour Agreement been repo...
488       q103b_15  Has the enterprise had any labour dispute the ...
491       q104c_15  Did you pay contribution to unemployment insur...
499        q106_15  Measures to ensure that your employees work ha...
674     q129b03_15                                        Labour code
732       EAq1d_13     Total labour costs 2013 (million VND), nominal
733       EAq1d_14     Total labour costs 2014 (million VND), nominal
755       EAq1dr13     Real total labor costs 2013 (million 2010 VND)
767       EAq1dr14     Real total labor costs 2014 (million 2010 VND)

In [ ]:
data2011 = df2011[
    [
        'id',
        'year',
        'qEAinetr10',
        'q73bb_11',
        'qEAqur10',
        'q101a1_11'
    ]
].copy()

In [ ]:
data2011.columns = [
    'id',
    'year',
    'profit',
    'credit',
    'assets',
    'labor'
]

In [ ]:
data2013 = df2013[
    [
        'id',
        'year',
        'EAq1inetr12',
        'q73bb_13',
        'EAq1qur12',
        'q101a1_13'
    ]
].copy()

In [ ]:
data2013.columns = [
    'id',
    'year',
    'profit',
    'credit',
    'assets',
    'labor'
]

In [ ]:
data2015 = df2015[
    [
        'id',
        'year',
        'EAq1enetr14',
        'q65bb_15',
        'EAq1hr14',
        'q90at_15'
    ]
].copy()

In [ ]:
data2015.columns = [
    'id',
    'year',
    'profit',
    'credit',
    'assets',
    'labor'
]

In [ ]:
import pandas as pd

panel = pd.concat(
    [
        data2011,
        data2013,
        data2015
    ],
    ignore_index=True
)

In [ ]:
panel.head()

   id  year      profit  credit        assets  labor
0   4  2011  620.000122   760.0   5480.000000   60.0
1   5  2011  147.300095   970.0   8615.000000   13.0
2  14  2011  387.500000  1920.0  20050.900391   40.0
3  24  2011  356.329865  1000.0   5200.000000   45.0
4  39  2011  172.200043    14.0    905.500000    7.0

In [ ]:
panel.shape

(7702, 6)

In [ ]:
panel['year'].value_counts().sort_index()

year
2011    2512
2013    2542
2015    2648
Name: count, dtype: int64

In [ ]:
panel.isnull().sum()

id          0
year        0
profit    375
credit      1
assets    187
labor       1
dtype: int64

In [ ]:
len(panel)

7702

In [ ]:
375/7702

0.04868865229810439

In [ ]:
panel_clean = panel.dropna()

In [ ]:
panel_clean = panel.dropna()

In [ ]:
panel_clean.isnull().sum()

id        0
year      0
profit    0
credit    0
assets    0
labor     0
dtype: int64

In [ ]:
panel_clean.shape

(7326, 6)

In [ ]:
panel_clean.describe()

,id,year,profit,credit,assets,labor
count,7326.000000,7326.000000,7326.000000,7326.000000,7326.000000,7326.000000
mean,6156.968878,2013.018837,536.377463,468.747944,4649.702393,15.798935
std,5255.542661,1.636170,5024.273998,7106.434605,17675.036956,38.777283
min,4.000000,2011.000000,-57272.257812,0.000000,0.743494,1.000000
25%,3617.500000,2011.000000,48.327137,0.000000,314.501259,3.000000
50%,6118.000000,2013.000000,101.621361,10.000000,1199.589355,5.000000
75%,8262.000000,2015.000000,257.419388,80.000000,3674.879028,12.000000
max,86091.000000,2015.000000,298776.625000,522605.656250,630393.437500,1700.000000

In [ ]:
panel_clean['year'].value_counts().sort_index()

year
2011    2417
2013    2423
2015    2486
Name: count, dtype: int64

In [ ]:
panel_clean

         id  year      profit  credit        assets  labor
0         4  2011  620.000122   760.0   5480.000000   60.0
1         5  2011  147.300095   970.0   8615.000000   13.0
2        14  2011  387.500000  1920.0  20050.900391   40.0
3        24  2011  356.329865  1000.0   5200.000000   45.0
4        39  2011  172.200043    14.0    905.500000    7.0
...     ...   ...         ...     ...           ...    ...
7697  86011  2015  139.630386     0.0    366.187561    3.0
7698  86051  2015  200.588684     0.0   4579.397949   30.0
7699  86071  2015  107.118416     0.0    166.324432    3.0
7700  86081  2015  148.227264    10.0    263.518158    4.0
7701  86091  2015   99.110207    50.0    967.145813    6.0

[7326 rows x 6 columns]

In [ ]:
panel_clean.to_excel(
    '/content/drive/MyDrive/SME_Project/panel_clean.xlsx',
    index=False
)

In [ ]:
import os

os.path.exists(
    '/content/drive/MyDrive/SME_Project/panel_clean.xlsx'
)

True

In [ ]:
panel.to_excel(
    '/content/drive/MyDrive/SME_Project/panel_raw.xlsx',
    index=False
)

In [ ]:
import os

os.path.exists(
    '/content/drive/MyDrive/SME_Project/panel_raw.xlsx'
)

True

In [ ]:
desc = panel_clean[['profit','credit','assets','labor']].describe()

desc.to_excel(
    '/content/drive/MyDrive/SME_Project/descriptive_statistics.xlsx'
)

In [ ]:
corr = panel_clean[
    ['profit','credit','assets','labor']
].corr()

corr

          profit    credit    assets     labor
profit  1.000000  0.342337  0.305775  0.217457
credit  0.342337  1.000000  0.579492  0.188422
assets  0.305775  0.579492  1.000000  0.392667
labor   0.217457  0.188422  0.392667  1.000000

In [ ]:
corr.to_excel(
    '/content/drive/MyDrive/SME_Project/correlation_matrix.xlsx'
)

In [ ]:
panel_clean.groupby('id')['year'].count().value_counts()

year
3    1545
1    1045
2     823
Name: count, dtype: int64

In [ ]:
!pip install linearmodels

Collecting linearmodels
  Downloading linearmodels-7.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Requirement already satisfied: numpy<3,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from linearmodels) (2.0.2)
Requirement already satisfied: pandas>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from linearmodels) (2.2.2)
Requirement already satisfied: scipy>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from linearmodels) (1.16.3)
Requirement already satisfied: statsmodels>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from linearmodels) (0.14.6)
Collecting mypy_extensions>=0.4 (from linearmodels)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Collecting pyhdfe>=0.1 (from linearmodels)
  Downloading pyhdfe-0.2.0-py3-none-any.whl.metadata (4.0 kB)
Collecting formulaic>=1.2.1 (from linearmodels)
  Downloading formulaic-1.2.2-py3-none-any.whl.metadata (7.0 kB)
Collecting interface-meta>=1.2.0 (from formulaic>=1.2.1->linearmodels)
  Downloading interface_meta-2.0.1-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: narwhals>=1.17 in /usr/local/lib/python3.12/dist-packages (from formulaic>=1.2.1->linearmodels) (2.22.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=1.2.1->linearmodels) (4.15.0)
Requirement already satisfied: wrapt>=1.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=1.2.1->linearmodels) (2.2.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.0->linearmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.0->linearmodels) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.0->linearmodels) (2026.2)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.13.0->linearmodels) (1.0.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.13.0->linearmodels) (26.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.4.0->linearmodels) (1.17.0)
Downloading linearmodels-7.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 6.3 MB/s eta 0:00:00
Downloading formulaic-1.2.2-py3-none-any.whl (118 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.9/118.9 kB 14.0 MB/s eta 0:00:00
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Downloading pyhdfe-0.2.0-py3-none-any.whl (19 kB)
Downloading interface_meta-2.0.1-py3-none-any.whl (15 kB)
Installing collected packages: mypy_extensions, interface-meta, pyhdfe, formulaic, linearmodels
Successfully installed formulaic-1.2.2 interface-meta-2.0.1 linearmodels-7.0 mypy_extensions-1.1.0 pyhdfe-0.2.0

In [ ]:
from linearmodels.panel import PanelOLS
import statsmodels.api as sm

In [ ]:
panel_fe = panel_clean.set_index(
    ['id','year']
)

In [ ]:
X = panel_fe[
    [
        'credit',
        'assets',
        'labor'
    ]
]

X = sm.add_constant(X)

y = panel_fe['profit']

model = PanelOLS(
    y,
    X,
    entity_effects=True
)

result = model.fit(
    cov_type='robust'
)

print(result)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                 profit   R-squared:                        0.0271
Estimator:                   PanelOLS   R-squared (Between):              0.0850
No. Observations:                7326   R-squared (Within):               0.0271
Date:                Thu, Jun 11 2026   R-squared (Overall):              0.0903
Time:                        17:58:20   Log-likelihood                -6.938e+04
Cov. Estimator:                Robust
                                        F-statistic:                      36.244
Entities:                        3413   P-value                           0.0000
Avg Obs:                       2.1465   Distribution:                  F(3,3910)
Min Obs:                       1.0000
Max Obs:                       3.0000   F-statistic (robust):             1.6244
                                        P-value                           0.1815
Time periods:                       3   Distribution:                  F(3,3910)
Avg Obs:                       2442.0
Min Obs:                       2417.0
Max Obs:                       2486.0

                             Parameter Estimates
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
const          401.24     154.65     2.5945     0.0095      98.040      704.43
credit         0.0649     0.0603     1.0766     0.2817     -0.0533      0.1832
assets         0.0280     0.0253     1.1081     0.2679     -0.0216      0.0777
labor         -1.6269     7.3476    -0.2214     0.8248     -16.032      12.779
==============================================================================

F-test for Poolability: 1.3566
P-value: 0.0000
Distribution: F(3412,3910)

Included effects: Entity

In [ ]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

vif = pd.DataFrame()

vif["Variable"] = X.columns

vif["VIF"] = [
    variance_inflation_factor(
        X.values,
        i
    )
    for i in range(X.shape[1])
]

print(vif)

  Variable       VIF
0    const  1.186503
1   credit  1.509709
2   assets  1.721552
3    labor  1.185526

In [ ]:
with open(
    '/content/drive/MyDrive/SME_Project/fixed_effects_result.txt',
    'w'
) as f:
    f.write(str(result.summary))

In [ ]:
panel_clean['id'].nunique()

3413

In [ ]:
panel_clean.groupby('id')['year'].count().value_counts().sort_index()

year
1    1045
2     823
3    1545
Name: count, dtype: int64

In [ ]:
(panel_clean.groupby('id')['year'].count() == 3).sum()

np.int64(1545)

In [ ]:
panel_clean.groupby('id')['year'].count().describe()

count    3413.000000
mean        2.146499
std         0.858847
min         1.000000
25%         1.000000
50%         2.000000
75%         3.000000
max         3.000000
Name: year, dtype: float64

In [ ]:
import pandas as pd

# 1. Thống kê mô tả
desc = panel_clean[['profit','credit','assets','labor']].describe()

# 2. Ma trận tương quan
corr = panel_clean[['profit','credit','assets','labor']].corr()

# 3. Cấu trúc panel
panel_structure = (
    panel_clean.groupby('id')['year']
    .count()
    .value_counts()
    .sort_index()
    .reset_index()
)

panel_structure.columns = [
    'Number_of_Years_Appearing',
    'Number_of_Firms'
]

# 4. Thông tin tổng quát mẫu
sample_info = pd.DataFrame({
    'Indicator': [
        'Total Observations',
        'Unique Firms',
        'Year 2011 Observations',
        'Year 2013 Observations',
        'Year 2015 Observations'
    ],
    'Value': [
        len(panel_clean),
        panel_clean['id'].nunique(),
        (panel_clean['year']==2011).sum(),
        (panel_clean['year']==2013).sum(),
        (panel_clean['year']==2015).sum()
    ]
})

# 5. Kết quả hồi quy FE
fe_result = pd.DataFrame({
    'Regression_Output': str(result.summary).split('\n')
})

# 6. Xuất Excel
with pd.ExcelWriter(
    '/content/drive/MyDrive/SME_Project/Research_Results.xlsx'
) as writer:

    sample_info.to_excel(
        writer,
        sheet_name='Sample_Info',
        index=False
    )

    panel_structure.to_excel(
        writer,
        sheet_name='Panel_Structure',
        index=False
    )

    desc.to_excel(
        writer,
        sheet_name='Descriptive_Statistics'
    )

    corr.to_excel(
        writer,
        sheet_name='Correlation_Matrix'
    )

    fe_result.to_excel(
        writer,
        sheet_name='Fixed_Effects_Result',
        index=False
    )

print("Xuất file thành công!")

Xuất file thành công!

In [ ]:
from google.colab import files

files.download(
    '/content/drive/MyDrive/SME_Project/Research_Results.xlsx'
)

In [ ]:
import numpy as np

panel_clean['ln_profit'] = np.log1p(panel_clean['profit'])

panel_clean['ln_credit'] = np.log1p(panel_clean['credit'])

panel_clean['ln_assets'] = np.log1p(panel_clean['assets'])

panel_clean['ln_labor'] = np.log1p(panel_clean['labor'])

/usr/local/lib/python3.12/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in log1p
  result = getattr(ufunc, method)(*inputs, **kwargs)
/tmp/ipykernel_1862/1913778228.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  panel_clean['ln_profit'] = np.log1p(panel_clean['profit'])
/tmp/ipykernel_1862/1913778228.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  panel_clean['ln_credit'] = np.log1p(panel_clean['credit'])
/tmp/ipykernel_1862/1913778228.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  panel_clean['ln_assets'] = np.log1p(panel_clean['assets'])
/tmp/ipykernel_1862/1913778228.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  panel_clean['ln_labor'] = np.log1p(panel_clean['labor'])

In [ ]:
panel_log = panel_clean.set_index(
    ['id','year']
)

In [ ]:
from linearmodels.panel import PanelOLS
import statsmodels.api as sm

X = panel_log[
    [
        'ln_credit',
        'ln_assets',
        'ln_labor'
    ]
]

X = sm.add_constant(X)

y = panel_log['ln_profit']

model = PanelOLS(
    y,
    X,
    entity_effects=True
)

result_log = model.fit(
    cov_type='robust'
)

print(result_log.summary)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:              ln_profit   R-squared:                        0.1071
Estimator:                   PanelOLS   R-squared (Between):              0.5913
No. Observations:                6997   R-squared (Within):               0.1071
Date:                Thu, Jun 11 2026   R-squared (Overall):              0.5220
Time:                        18:14:31   Log-likelihood                   -5679.7
Cov. Estimator:                Robust
                                        F-statistic:                      145.97
Entities:                        3343   P-value                           0.0000
Avg Obs:                       2.0930   Distribution:                  F(3,3651)
Min Obs:                       1.0000
Max Obs:                       3.0000   F-statistic (robust):             83.970
                                        P-value                           0.0000
Time periods:                       3   Distribution:                  F(3,3651)
Avg Obs:                       2332.3
Min Obs:                       2315.0
Max Obs:                       2341.0

                             Parameter Estimates
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
const          2.3974     0.1593     15.049     0.0000      2.0851      2.7097
ln_credit      0.0019     0.0096     0.1993     0.8420     -0.0170      0.0208
ln_assets      0.1998     0.0194     10.281     0.0000      0.1617      0.2379
ln_labor       0.5371     0.0519     10.348     0.0000      0.4354      0.6389
==============================================================================

F-test for Poolability: 2.1420
P-value: 0.0000
Distribution: F(3342,3651)

Included effects: Entity

/usr/local/lib/python3.12/dist-packages/linearmodels/panel/model.py:1258: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  super().__init__(dependent, exog, weights=weights, check_rank=check_rank)

In [ ]:
coef_table = pd.DataFrame({
    'Variable': result_log.params.index,
    'Coefficient': result_log.params.values,
    'P_value': result_log.pvalues.values
})

coef_table

    Variable  Coefficient   P_value
0      const     2.397395  0.000000
1  ln_credit     0.001921  0.842034
2  ln_assets     0.199833  0.000000
3   ln_labor     0.537145  0.000000

In [ ]:
coef_table.to_excel(
    '/content/drive/MyDrive/SME_Project/Regression_Log_Result.xlsx',
    index=False
)

In [ ]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

X_vif = panel_clean[
    ['ln_credit',
     'ln_assets',
     'ln_labor']
]

vif = pd.DataFrame()

vif["Variable"] = X_vif.columns

vif["VIF"] = [
    variance_inflation_factor(
        X_vif.values,
        i
    )
    for i in range(X_vif.shape[1])
]

print(vif)

    Variable        VIF
0  ln_credit   3.093714
1  ln_assets   9.851028
2   ln_labor  11.421800

In [ ]:
import pandas as pd

coef_table = pd.DataFrame({
    'Coefficient': result_log.params,
    'Std_Error': result_log.std_errors,
    'T_Statistic': result_log.tstats,
    'P_Value': result_log.pvalues,
    'CI_Lower': result_log.conf_int().iloc[:,0],
    'CI_Upper': result_log.conf_int().iloc[:,1]
})

coef_table

           Coefficient  Std_Error  T_Statistic   P_Value  CI_Lower  CI_Upper
const         2.397395   0.159309    15.048708  0.000000  2.085051  2.709738
ln_credit     0.001921   0.009638     0.199307  0.842034 -0.016975  0.020817
ln_assets     0.199833   0.019438    10.280598  0.000000  0.161722  0.237943
ln_labor      0.537145   0.051907    10.348134  0.000000  0.435375  0.638915

In [ ]:
model_info = pd.DataFrame({
    'Statistic': [
        'Number of Observations',
        'Number of Firms',
        'R-squared Within',
        'R-squared Between',
        'R-squared Overall',
        'F-statistic Robust',
        'Prob(F-statistic)',
        'Poolability Test',
        'Poolability P-value'
    ],
    'Value': [
        result_log.nobs,
        panel_clean['id'].nunique(),
        result_log.rsquared_within,
        result_log.rsquared_between,
        result_log.rsquared_overall,
        result_log.f_statistic.stat,
        result_log.f_statistic.pval,
        result_log.f_pooled.stat,
        result_log.f_pooled.pval
    ]
})

In [ ]:
with pd.ExcelWriter(
    '/content/drive/MyDrive/SME_Project/Log_FE_Results.xlsx'
) as writer:

    coef_table.to_excel(
        writer,
        sheet_name='Regression_Coefficients'
    )

    model_info.to_excel(
        writer,
        sheet_name='Model_Information',
        index=False
    )

    desc.to_excel(
        writer,
        sheet_name='Descriptive_Statistics'
    )

    corr.to_excel(
        writer,
        sheet_name='Correlation_Matrix'
    )

print("Đã xuất thành công!")

Đã xuất thành công!

In [ ]:
from google.colab import files

files.download(
    '/content/drive/MyDrive/SME_Project/Log_FE_Results.xlsx'
)

In [ ]:
import pandas as pd

# ====== BẢNG HỆ SỐ HỒI QUY ======
coef_table = pd.DataFrame({
    'Coefficient': result_log.params,
    'Std_Error': result_log.std_errors,
    'T_Statistic': result_log.tstats,
    'P_Value': result_log.pvalues,
    'CI_Lower': result_log.conf_int().iloc[:,0],
    'CI_Upper': result_log.conf_int().iloc[:,1]
})

# ====== THÔNG TIN MÔ HÌNH ======
model_info = pd.DataFrame({
    'Statistic': [
        'Number of Observations',
        'Number of Firms',
        'R-squared Within',
        'R-squared Between',
        'R-squared Overall',
        'F-statistic Robust',
        'Prob(F-statistic)',
        'Poolability Test',
        'Poolability P-value'
    ],
    'Value': [
        result_log.nobs,
        panel_clean['id'].nunique(),
        result_log.rsquared_within,
        result_log.rsquared_between,
        result_log.rsquared_overall,
        result_log.f_statistic.stat,
        result_log.f_statistic.pval,
        result_log.f_pooled.stat,
        result_log.f_pooled.pval
    ]
})

# ====== XUẤT FILE ======
with pd.ExcelWriter(
    '/content/drive/MyDrive/SME_Project/Final_Research_Output.xlsx'
) as writer:

    desc.to_excel(
        writer,
        sheet_name='Descriptive_Statistics'
    )

    corr.to_excel(
        writer,
        sheet_name='Correlation_Matrix'
    )

    vif.to_excel(
        writer,
        sheet_name='VIF_Test',
        index=False
    )

    coef_table.to_excel(
        writer,
        sheet_name='FE_Log_Result'
    )

    model_info.to_excel(
        writer,
        sheet_name='Model_Information',
        index=False
    )

print("Đã tạo file Final_Research_Output.xlsx")

Đã tạo file Final_Research_Output.xlsx

In [ ]:
from google.colab import files

files.download(
    '/content/drive/MyDrive/SME_Project/Final_Research_Output.xlsx'
)